name: CI
on: [push]
jobs:
  deploy:
   if: github.ref == 'refs/heads/master'
   runs-on: [ubuntu-latest]
   steps:
     - uses: actions/checkout@v1
     - name: Push to server
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.ip }}
          username: ${{ secrets.nome }}
          password: ${{ secrets.pass }}
          script: |
                 ls -la
                 cd /documents/
                 sudo git clone "https://github.com/D45putspin/edly"
                 sudo rm -rf edly_web
                 sudo mv -T edly edly_web
                 cd edly_web
                 npm install
                 npm start
